// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDotxhIn95vO_g5VrE4f2ye9FjZ7O4QM-4',
    appId: '1:914898549093:web:5872d76d700533521b898c',
    messagingSenderId: '914898549093',
    projectId: 'inscribe-app-c3ccf',
    authDomain: 'inscribe-app-c3ccf.firebaseapp.com',
    storageBucket: 'inscribe-app-c3ccf.appspot.com',
    measurementId: 'G-W8L9LDXJ1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgR7a79kcJTv0jgFmouBWWMThL6sZigwQ',
    appId: '1:914898549093:android:8770978d2f1d80101b898c',
    messagingSenderId: '914898549093',
    projectId: 'inscribe-app-c3ccf',
    storageBucket: 'inscribe-app-c3ccf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmbxmUp_-igQ92sSPCgCfSYp97cYyIGxo',
    appId: '1:914898549093:ios:d98a7d0382b0c8b01b898c',
    messagingSenderId: '914898549093',
    projectId: 'inscribe-app-c3ccf',
    storageBucket: 'inscribe-app-c3ccf.appspot.com',
    iosBundleId: 'com.example.inscribe',
  );
}
