name: inscribe
description: "Celebrate friendships with personalized notes on likes, birthdays, and gift ideas."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.2
  firebase_analytics: ^10.9.0
  firebase_performance: ^0.9.3+19
  firebase_remote_config: ^4.3.19
  slang: ^3.30.2
  go_router: ^14.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  slang_flutter: ^3.30.0
  get_it: ^7.6.7
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  firebase_crashlytics: ^3.5.0
  google_fonts: ^6.2.1
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter:
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  build_runner: ^2.4.9 
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile_images/
    # - google_fonts/

  fonts:
    - family: Brogi
      fonts:
        - asset: assets/fonts/brogi_regular.otf

